### ISSUE TITLE
Sometimes pyds9 breaks and you need to restart computer

### ISSUE THREAD

**Issue by paxsonswierc** [paxsonswierc/galfit_wrapper#22]
Probably due to timeout? 
raise ValueError('no active ds9 running for target: %s' % target)
ValueError: no active ds9 running for target: ds9

**Comment by paxsonswierc** [comment]
Traceback (most recent call last):
  File "/Users/pswierc/galfit_scripts/galfit_wrapper/galfit_wrapper.py", line 456, in <module>
    d = pyds9.DS9()
        ^^^^^^^^^^^
  File "/Users/pswierc/anaconda3/envs/field_course/lib/python3.12/site-packages/pyds9.py", line 449, in __init__
    raise ValueError('no active ds9 running for target: %s' % target)
